# Generated by Django 5.0.3 on 2024-03-26 01:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="curso",
            name="duracion",
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="curso",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("publicado", "Publicado"),
                    ("archivado", "Archivado"),
                ],
                default="Publicado",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="curso",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cursos.categoria",
            ),
        ),
    ]
