# Generated by Django 5.0.3 on 2024-03-27 00:14

import cursos.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0004_inscripcion_curso_estudiantes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscripcion",
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
            },
        ),
        migrations.AlterField(
            model_name="curso",
            name="duracion",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                validators=[cursos.models.duracion_minima],
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="fecha_publicacion",
            field=models.DateField(verbose_name="Fecha de publicación"),
        ),
        migrations.AlterField(
            model_name="curso",
            name="precio",
            field=models.IntegerField(validators=[cursos.models.precio_positivo]),
        ),
    ]
