# Generated by Django 5.0.3 on 2024-04-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0005_alter_inscripcion_options_alter_curso_duracion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="cursos/curso/fallback.png",
                upload_to="cursos/curso",
            ),
        ),
    ]
