# Generated by Django 5.0.3 on 2024-04-19 00:00

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0007_estudiante_avatar_instructor_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="contenido",
            field=tinymce.models.HTMLField(default=""),
        ),
    ]
