# Generated by Django 5.0.3 on 2024-04-19 00:21

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0008_curso_contenido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="descripcion",
            field=models.CharField(max_length=255, verbose_name="Descripción breve"),
        ),
        migrations.AlterField(
            model_name="curso",
            name="requisitos",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
    ]
