# Generated by Django 5.0.3 on 2024-04-26 00:00

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0009_alter_curso_descripcion_alter_curso_requisitos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructor",
            name="nombre",
        ),
        migrations.AddField(
            model_name="instructor",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="cursos/usuario/fallback.png",
                upload_to="cursos/usuario",
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="bio",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
    ]
